//action types
// Action Types

// GET
export const GET_UPLOADED_FILES_REQUEST = "GET_UPLOADED_FILES_REQUEST";
export const GET_UPLOADED_FILES_SUCCESS = "GET_UPLOADED_FILES_SUCCESS";
export const GET_UPLOADED_FILES_FAILURE = "GET_UPLOADED_FILES_FAILURE";

// POST
export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";

// DELETE
export const DELETE_UPLOADED_FILE_REQUEST = "DELETE_UPLOADED_FILE_REQUEST";
export const DELETE_UPLOADED_FILE_SUCCESS = "DELETE_UPLOADED_FILE_SUCCESS";
export const DELETE_UPLOADED_FILE_FAILURE = "DELETE_UPLOADED_FILE_FAILURE";


export const FILES_SELECTION_SUCCESS = "FILES_SELECTION_SUCCESS";