export const GENERATE_RESPONSE_REQUEST = "GENERATE_RESPONSE_REQUEST";
export const GENERATE_RESPONSE_SUCCESS = "GENERATE_RESPONSE_SUCCESS";
export const GENERATE_RESPONSE_FAILURE = "GENERATE_RESPONSE_FAILURE";
